#!/opt/ruby/current/bin/ruby
require 'rubygems'
version = ">= 14.2.0"
if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/
    version = $1
    ARGV.shift
  end
end
gem 'automatic', version
load Gem.bin_path('automatic', 'automatic', version)
